name: Build

on: [push, pull_request]


jobs:
  build:
    name: Build on 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        dotnet: ['2.2.103', '3.0.100' ]

    steps:
      - name: Get the sources
        uses: actions/checkout@v1
    
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.0.100'
            
      - name: Build with dotnet
        run: dotnet build --configuration Release
